### PR TITLE
Fix #23: Add Vue 3 support

### LINKED ISSUE #23: Feature: Vue 3 support
When trying to install VueSSE with Vue 3, you may receive a warning:

> vue-sse@2.2.0" has incorrect peer dependency "vue@^2.0.0".

When trying to use according to the instructions, an error occurs:

> Uncaught TypeError: Vue.prototype is undefined

Are you planning to add support for Vue 3 (including the Composition API)? 

Thanks!

### PR DESCRIPTION
**Pull request by clayadavis**
Towards #23 this PR adds basic Vue 3 support, but doesn't touch Composition API.

Built `dist/` files are included for ease of testing, but the real diff is just a few lines in `src/sse-manager.js`

### CODE REVIEW

File: src/sse-manager.js [hunk 1]
```diff
@@ -1,8 +1,15 @@
...
-  Vue.$sse = Vue.prototype.$sse = new SSEManager(config);
+
+  try {
+    // Vue2
+    // eslint-disable-next-line no-param-reassign, no-multi-assign
+    Vue.$sse = Vue.prototype.$sse = new SSEManager(config);
+  } catch (e) {
+    // Vue3
+    Vue.config.globalProperties.$sse = new SSEManager(config);
+  }
```
Comment (tserkov) [inline src/sse-manager.js]: I would greatly prefer checking if object properties exist (`if (Vue.config && Vue.config.globalProperties) { ... }`) rather than a try/catch.

File: dist/vue-sse.common.js [hunk 2]
```diff
@@ -1,5 +1,5 @@
 /*!
- * vue-sse v2.2.0
+ * vue-sse v2.3.0
```
Comment (tserkov) [inline dist/vue-sse.common.js]: This version will actually be 2.4.0

**Review by tserkov — CHANGES_REQUESTED** [review]
Hi Clay,

Thanks for tackling this. I've made one change request, and then we'll get this merged.

If you'd like to save me a commit, you can go ahead and increment package.json to 2.4.0 as well.

Thanks again!

**Review by tserkov — APPROVED** [review]
Looks good!

Let me get 2.3.1 out the door (fixes bug in forcePolyfill) and then I'll push this out right after.
